const BusinessConfig = [
    'A&R Administrator',
    'A&R Coordinator',
    'Accompanist',
    'Advance Person',
    'Album Cover Designer',
    'Arranger',
    'Artist Relations and Development Representative',
    'Assistant Engineer',
    'Audio Engineer',
    'Background Singer',
    'Band Director',
    'Booking Agent',
    'Business Manager',
    'Campus Representative',
    'Cantor',
    'Celebrity Bodyguard',
    'Choir Director',
    'Choreographer',
    'Church Organist',
    'College',
    'Composer',
    'Concert Hall Manager',
    'Concert Hall Marketing Director',
    'Concert Promoter',
    'Concertmaster',
    'Conductor',
    'Consumer Researcher',
    'Copyist',
    'Cruise Ship Musician',
]

export default BusinessConfig;